FROM python:3.7-alpine as base

COPY requirements.txt requirements.txt

RUN pip install  -r requirements.txt

RUN mkdir /app

COPY event_query.py /app

WORKDIR /app

EXPOSE 5000

CMD ["python3", "event_query.py"]